# **1. Load Dataset**

In [1]:
import pandas as pd
import numpy as n
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
# NLP
import nltk
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
# Scikit-Learn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Display Settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 300)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
file_path = "/content/drive/MyDrive/Data/arxiv_ai_ml_papers.csv"

df = pd.read_csv(file_path)

print(f"Dataset Loaded Successfully")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

Dataset Loaded Successfully
Rows: 7,701
Columns: 26

In [3]:
df.head()

,paper_id,title,authors,num_authors,first_author,abstract,abstract_length,word_count,primary_category,all_categories,num_categories,submitted_date,updated_date,year,month,has_journal_ref,journal_ref,comment,has_doi,doi,arxiv_url,pdf_url,is_large_collaboration,is_updated,update_lag_days,days_since_submission
0,2604.26951v1,Turning the TIDE: Cross-Architecture Distillation for Diffusion Large Language Models,Gongbo Zhang; Wen Wang; Ye Tian; Li Yuan,4,Gongbo Zhang,"Diffusion large language models (dLLMs) offer parallel decoding and bidirectional context, but state-of-the-art dLLMs require billions of parameters for competitive performance. While existing distillation methods for dLLMs reduce inference steps within a single architecture, none address cross-...",1269,167,cs.CL,cs.CL; cs.AI; cs.LG,3,2026-04-29,2026-04-29,2026,4,0,Not Available,"15 pages, 3 figures. Code: https://github.com/PKU-YuanGroup/TIDE",0,Not Available,https://arxiv.org/abs/2604.26951v1,https://arxiv.org/pdf/2604.26951v1,0,0,0,1
1,2604.26231v1,ProMax: Exploring the Potential of LLM-derived Profiles with Distribution Shaping for Recommender Systems,Yi Zhang; Yiwen Zhang; Kai Zheng; Tong Chen; Hongzhi Yin,5,Yi Zhang,"The remarkable text understanding and generation capabilities of large language models (LLMs) have revitalized the field of general recommendation based on implicit user feedback. Rather than deploying LLMs directly as recommendation models, a more flexible paradigm leverages their ability to in...",1748,233,cs.IR,cs.IR,1,2026-04-29,2026-04-29,2026,4,0,Not Available,"11 pages, 8 figures, accepted by SIGIR 2026",0,Not Available,https://arxiv.org/abs/2604.26231v1,https://arxiv.org/pdf/2604.26231v1,0,0,0,1
2,2604.26567v1,AirZoo: A Unified Large-Scale Dataset for Grounding Aerial Geometric 3D Vision,Xiaoya Cheng; Rouwan Wu; Xinyi Liu; Zeyu Cui; Yan Liu; Na Zhao; Yu Liu; Maojun Zhang; Shen Yan,9,Xiaoya Cheng,"Despite the rapid progress in data-driven 3D vision, aerial geometric 3D vision remains a formidable challenge due to the severe scarcity of large-scale, high-fidelity training data. Existing benchmarks, predominantly biased toward ground-level or object-centric views, do not account for complex...",1692,217,cs.CV,cs.CV,1,2026-04-29,2026-04-29,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.26567v1,https://arxiv.org/pdf/2604.26567v1,0,0,0,1
3,2604.26565v1,"DenseStep2M: A Scalable, Training-Free Pipeline for Dense Instructional Video Annotation",Mingji Ge; Qirui Chen; Zeqian Li; Weidi Xie,4,Mingji Ge,"Long-term video understanding requires interpreting complex temporal events and reasoning over procedural activities. While instructional video corpora, like HowTo100M, offer rich resources for model training, they present significant challenges, including noisy ASR transcripts and inconsistent ...",1758,204,cs.CV,cs.CV,1,2026-04-29,2026-04-29,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.26565v1,https://arxiv.org/pdf/2604.26565v1,0,0,0,1
4,2604.26520v1,3D-LENS: A 3D Lifting-based Elevated Novel-view Synthesis method for Single-View Aerial-Ground Re-Identification,William Grolleau; Astrid Sabourin; Guillaume Lapouge; Catherine Achard,4,William Grolleau,"Aerial-Ground Re-Identification (AG-ReID) is constrained by the viewpoint-domain gap, as drastic viewpoint disparities occlude or distort discriminative features, making cross-viewpoint image retrieval challenging. While existing methods rely on paired cross-view annotations, real-world deployme...",1418,174,cs.CV,cs.CV,1,2026-04-29,2026-04-29,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.26520v1,https://arxiv.org/pdf/2604.26520v1,0,0,0,1

In [4]:
df.sample(5, random_state=42)

,paper_id,title,authors,num_authors,first_author,abstract,abstract_length,word_count,primary_category,all_categories,num_categories,submitted_date,updated_date,year,month,has_journal_ref,journal_ref,comment,has_doi,doi,arxiv_url,pdf_url,is_large_collaboration,is_updated,update_lag_days,days_since_submission
3856,2604.16123v2,Tabular foundation models for in-context prediction of molecular properties,Karim K. Ben Hicham; Jan G. Rittig; Martin Grohe; Alexander Mitsos,4,Karim K. Ben Hicham,"Accurate molecular property prediction is central to drug discovery, catalysis, and process design, yet real-world applications are often limited by small datasets. Molecular foundation models provide a promising direction by learning transferable molecular representations; however, they typical...",1668,209,cs.LG,cs.LG; physics.chem-ph,2,2026-04-17,2026-04-20,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.16123v2,https://arxiv.org/pdf/2604.16123v2,0,1,3,13
5546,2604.08079v1,Search Changes Consumers' Minds: How Recognizing Gaps Drives Sustainable Choices,Frans van der Sluis; Leif Azzopardi,2,Frans van der Sluis,"Despite a growing desire among consumers to shop responsibly, translating this intention into behaviour remains challenging. Previous work has identified that information seeking (or lack thereof) is a contributing factor to this intention-behaviour gap.In this paper, we hypothesize that searchi...",1350,189,cs.IR,cs.IR; cs.HC,2,2026-04-09,2026-04-09,2026,4,1,"In CHIIR '25: Proceedings of the 2025 ACM SIGIR Conference on Human Information Interaction and Retrieval, Melbourne, VIC, Australia, March 24-28, 2025, ACM, pp. 195-207","17 pages, 5 figures, supplementary appendix. Accepted at CHIIR '25 (2025 ACM SIGIR Conference on Human Information Interaction and Retrieval). Peer reviewed",1,10.1145/3698204.3716456,https://arxiv.org/abs/2604.08079v1,https://arxiv.org/pdf/2604.08079v1,0,0,0,21
6008,2604.01042v1,Integer-State Dynamics of Quantized Spiking Neural Networks for Efficient Hardware Acceleration,Lei Zhang,1,Lei Zhang,"Spiking neural networks (SNNs) support energy-efficient machine intelligence because event-driven computation and sparse activity map naturally to low-power digital hardware. In practical implementations, however, membrane states, synaptic weights, and thresholds are represented with finite-prec...",1407,181,cs.NE,cs.NE; nlin.CD,2,2026-04-01,2026-04-01,2026,4,0,Not Available,"14 pages, 7 figures, submitted to Electronics (MDPI) and currently under review",0,Not Available,https://arxiv.org/abs/2604.01042v1,https://arxiv.org/pdf/2604.01042v1,0,0,0,29
7573,2510.22417v1,Genetic Optimization of a Software-Defined GNSS Receiver,Laura Train; Rodrigo Castellanos; Miguel Gómez-López,3,Laura Train,"Commercial off-the-shelf (COTS) Global Navigation Satellite System (GNSS) receivers face significant limitations under high-dynamic conditions, particularly in high-acceleration environments such as those experienced by launch vehicles. These performance degradations, often observed as discontin...",1552,204,eess.SP,eess.SP; cs.NE; math.OC,3,2025-10-25,2025-10-25,2025,10,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2510.22417v1,https://arxiv.org/pdf/2510.22417v1,0,0,0,187
1488,2604.22967v1,Rethinking Trust Region Bayesian Optimization in High Dimensions,Wei-Ting Tang; Joel A. Paulson,2,Wei-Ting Tang,"Trust Region Bayesian Optimization (TuRBO) is an effective strategy for alleviating the curse of dimensionality in high-dimensional black-box optimization. However, inappropriate lengthscale design can cause the local Gaussian process (GP) model within the trust region to degenerate, leading to ...",933,129,stat.ML,stat.ML; cs.LG,2,2026-04-24,2026-04-24,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.22967v1,https://arxiv.org/pdf/2604.22967v1,0,0,0,6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7701 entries, 0 to 7700
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   paper_id                7701 non-null   object
 1   title                   7701 non-null   object
 2   authors                 7701 non-null   object
 3   num_authors             7701 non-null   int64
 4   first_author            7701 non-null   object
 5   abstract                7701 non-null   object
 6   abstract_length         7701 non-null   int64
 7   word_count              7701 non-null   int64
 8   primary_category        7701 non-null   object
 9   all_categories          7701 non-null   object
 10  num_categories          7701 non-null   int64
 11  submitted_date          7701 non-null   object
 12  updated_date            7701 non-null   object
 13  year                    7701 non-null   int64
 14  month                   7701 non-null   int64
 15  has_journal_ref         7701 non-null   int64
 16  journal_ref             7701 non-null   object
 17  comment                 7701 non-null   object
 18  has_doi                 7701 non-null   int64
 19  doi                     7701 non-null   object
 20  arxiv_url               7701 non-null   object
 21  pdf_url                 7701 non-null   object
 22  is_large_collaboration  7701 non-null   int64
 23  is_updated              7701 non-null   int64
 24  update_lag_days         7701 non-null   int64
 25  days_since_submission   7701 non-null   int64
dtypes: int64(12), object(14)
memory usage: 1.5+ MB

In [6]:
print(f"Number of Papers: {len(df):,}")
print(f"Number of Features: {df.shape[1]}")

Number of Papers: 7,701
Number of Features: 26

In [7]:
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

1. paper_id
2. title
3. authors
4. num_authors
5. first_author
6. abstract
7. abstract_length
8. word_count
9. primary_category
10. all_categories
11. num_categories
12. submitted_date
13. updated_date
14. year
15. month
16. has_journal_ref
17. journal_ref
18. comment
19. has_doi
20. doi
21. arxiv_url
22. pdf_url
23. is_large_collaboration
24. is_updated
25. update_lag_days
26. days_since_submission

# **2. Data Audit**

In [8]:
missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": round(df.isnull().mean()*100, 2)
})

missing_report.sort_values(
    by="Missing Values",
    ascending=False
)

                        Missing Values  Missing Percentage
paper_id                             0                 0.0
title                                0                 0.0
authors                              0                 0.0
num_authors                          0                 0.0
first_author                         0                 0.0
abstract                             0                 0.0
abstract_length                      0                 0.0
word_count                           0                 0.0
primary_category                     0                 0.0
all_categories                       0                 0.0
num_categories                       0                 0.0
submitted_date                       0                 0.0
updated_date                         0                 0.0
year                                 0                 0.0
month                                0                 0.0
has_journal_ref                      0                 0.0
journal_ref                          0                 0.0
comment                              0                 0.0
has_doi                              0                 0.0
doi                                  0                 0.0
arxiv_url                            0                 0.0
pdf_url                              0                 0.0
is_large_collaboration               0                 0.0
is_updated                           0                 0.0
update_lag_days                      0                 0.0
days_since_submission                0                 0.0

In [9]:

print(
    f"Duplicate Rows: {df.duplicated().sum()}"
)

Duplicate Rows: 0

In [10]:
unique_report = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique_report.sort_values(
    by="Unique Values",
    ascending=False
)

                        Unique Values
paper_id                         7701
title                            7701
abstract                         7701
arxiv_url                        7701
pdf_url                          7701
authors                          7503
first_author                     7037
comment                          3224
all_categories                   1597
abstract_length                  1306
doi                               339
word_count                        240
journal_ref                       235
days_since_submission             211
submitted_date                    211
updated_date                      209
update_lag_days                   113
primary_category                  107
num_authors                        59
month                               8
num_categories                      6
year                                2
has_journal_ref                     2
has_doi                             2
is_updated                          2
is_large_collaboration              2

In [11]:
print("Submitted Date")

print(df["submitted_date"].min())
print(df["submitted_date"].max())

print("\nUpdated Date")

print(df["updated_date"].min())
print(df["updated_date"].max())

Submitted Date
2025-09-27
2026-04-29

Updated Date
2025-09-28
2026-04-29

In [12]:
df["submitted_date"] = pd.to_datetime(
    df["submitted_date"]
)

df["updated_date"] = pd.to_datetime(
    df["updated_date"]
)

print("Dates Converted Successfully")

Dates Converted Successfully

In [13]:
df[
    ["submitted_date", "updated_date"]
].dtypes

submitted_date    datetime64[ns]
updated_date      datetime64[ns]
dtype: object

In [14]:
df.describe()

,num_authors,abstract_length,word_count,num_categories,submitted_date,updated_date,year,month,has_journal_ref,has_doi,is_large_collaboration,is_updated,update_lag_days,days_since_submission
count,7701.000000,7701.000000,7701.000000,7701.000000,7701,7701,7701.000000,7701.000000,7701.000000,7701.000000,7701.000000,7701.000000,7701.000000,7701.000000
mean,5.121932,1362.295936,179.698351,2.076094,2026-04-03 13:57:20.124658944,2026-04-05 13:52:28.422282752,2025.945981,4.150889,0.031554,0.043890,0.002208,0.108947,1.996624,26.418517
min,1.000000,147.000000,22.000000,1.000000,2025-09-27 00:00:00,2025-09-28 00:00:00,2025.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,3.000000,1153.000000,152.000000,1.000000,2026-04-06 00:00:00,2026-04-07 00:00:00,2026.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000
50%,4.000000,1364.000000,179.000000,2.000000,2026-04-17 00:00:00,2026-04-18 00:00:00,2026.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.000000
75%,6.000000,1591.000000,208.000000,3.000000,2026-04-23 00:00:00,2026-04-23 00:00:00,2026.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000
max,547.000000,2031.000000,295.000000,6.000000,2026-04-29 00:00:00,2026-04-29 00:00:00,2026.000000,12.000000,1.000000,1.000000,1.000000,1.000000,197.000000,215.000000
std,9.899800,308.505215,40.948898,1.021802,NaN,NaN,0.226070,1.711712,0.174822,0.204865,0.046935,0.311593,12.539827,39.861510

In [15]:
print(
    f"Primary Categories: {df['primary_category'].nunique()}"
)

print(
    f"First Authors: {df['first_author'].nunique()}"
)

Primary Categories: 107
First Authors: 7037

In [16]:
large_collab_count = (
    df["is_large_collaboration"]
    .sum()
)

print(
    f"Large Collaboration Papers: {large_collab_count:,}"
)

Large Collaboration Papers: 17

In [17]:
large_collab_percentage = (
    df["is_large_collaboration"]
    .mean() * 100
)

print(
    f"Large Collaboration Rate: {large_collab_percentage:.2f}%"
)

Large Collaboration Rate: 0.22%

In [18]:
df["primary_category"].value_counts().head(10)

primary_category
cs.CV      1418
cs.LG      1392
cs.CL      1119
cs.RO       633
cs.AI       555
cs.NE       511
cs.IR       456
stat.ML     398
cs.CR       149
cs.SE        93
Name: count, dtype: int64

In [19]:
feature_dictionary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values
})

feature_dictionary

                    Column       Data Type
0                 paper_id          object
1                    title          object
2                  authors          object
3              num_authors           int64
4             first_author          object
5                 abstract          object
6          abstract_length           int64
7               word_count           int64
8         primary_category          object
9           all_categories          object
10          num_categories           int64
11          submitted_date  datetime64[ns]
12            updated_date  datetime64[ns]
13                    year           int64
14                   month           int64
15         has_journal_ref           int64
16             journal_ref          object
17                 comment          object
18                 has_doi           int64
19                     doi          object
20               arxiv_url          object
21                 pdf_url          object
22  is_large_collaboration           int64
23              is_updated           int64
24         update_lag_days           int64
25   days_since_submission           int64

In [20]:
categorical_cols = df.select_dtypes(
    include="object"
).columns.tolist()

numerical_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

datetime_cols = df.select_dtypes(
    include=["datetime64[ns]"]
).columns.tolist()

print("Categorical Columns")
print(categorical_cols)

print("\nNumerical Columns")
print(numerical_cols)

print("\nDatetime Columns")
print(datetime_cols)

Categorical Columns
['paper_id', 'title', 'authors', 'first_author', 'abstract', 'primary_category', 'all_categories', 'journal_ref', 'comment', 'doi', 'arxiv_url', 'pdf_url']

Numerical Columns
['num_authors', 'abstract_length', 'word_count', 'num_categories', 'year', 'month', 'has_journal_ref', 'has_doi', 'is_large_collaboration', 'is_updated', 'update_lag_days', 'days_since_submission']

Datetime Columns
['submitted_date', 'updated_date']

# **3. EDA**

In [21]:
df

,paper_id,title,authors,num_authors,first_author,abstract,abstract_length,word_count,primary_category,all_categories,num_categories,submitted_date,updated_date,year,month,has_journal_ref,journal_ref,comment,has_doi,doi,arxiv_url,pdf_url,is_large_collaboration,is_updated,update_lag_days,days_since_submission
0,2604.26951v1,Turning the TIDE: Cross-Architecture Distillation for Diffusion Large Language Models,Gongbo Zhang; Wen Wang; Ye Tian; Li Yuan,4,Gongbo Zhang,"Diffusion large language models (dLLMs) offer parallel decoding and bidirectional context, but state-of-the-art dLLMs require billions of parameters for competitive performance. While existing distillation methods for dLLMs reduce inference steps within a single architecture, none address cross-...",1269,167,cs.CL,cs.CL; cs.AI; cs.LG,3,2026-04-29,2026-04-29,2026,4,0,Not Available,"15 pages, 3 figures. Code: https://github.com/PKU-YuanGroup/TIDE",0,Not Available,https://arxiv.org/abs/2604.26951v1,https://arxiv.org/pdf/2604.26951v1,0,0,0,1
1,2604.26231v1,ProMax: Exploring the Potential of LLM-derived Profiles with Distribution Shaping for Recommender Systems,Yi Zhang; Yiwen Zhang; Kai Zheng; Tong Chen; Hongzhi Yin,5,Yi Zhang,"The remarkable text understanding and generation capabilities of large language models (LLMs) have revitalized the field of general recommendation based on implicit user feedback. Rather than deploying LLMs directly as recommendation models, a more flexible paradigm leverages their ability to in...",1748,233,cs.IR,cs.IR,1,2026-04-29,2026-04-29,2026,4,0,Not Available,"11 pages, 8 figures, accepted by SIGIR 2026",0,Not Available,https://arxiv.org/abs/2604.26231v1,https://arxiv.org/pdf/2604.26231v1,0,0,0,1
2,2604.26567v1,AirZoo: A Unified Large-Scale Dataset for Grounding Aerial Geometric 3D Vision,Xiaoya Cheng; Rouwan Wu; Xinyi Liu; Zeyu Cui; Yan Liu; Na Zhao; Yu Liu; Maojun Zhang; Shen Yan,9,Xiaoya Cheng,"Despite the rapid progress in data-driven 3D vision, aerial geometric 3D vision remains a formidable challenge due to the severe scarcity of large-scale, high-fidelity training data. Existing benchmarks, predominantly biased toward ground-level or object-centric views, do not account for complex...",1692,217,cs.CV,cs.CV,1,2026-04-29,2026-04-29,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.26567v1,https://arxiv.org/pdf/2604.26567v1,0,0,0,1
3,2604.26565v1,"DenseStep2M: A Scalable, Training-Free Pipeline for Dense Instructional Video Annotation",Mingji Ge; Qirui Chen; Zeqian Li; Weidi Xie,4,Mingji Ge,"Long-term video understanding requires interpreting complex temporal events and reasoning over procedural activities. While instructional video corpora, like HowTo100M, offer rich resources for model training, they present significant challenges, including noisy ASR transcripts and inconsistent ...",1758,204,cs.CV,cs.CV,1,2026-04-29,2026-04-29,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.26565v1,https://arxiv.org/pdf/2604.26565v1,0,0,0,1
4,2604.26520v1,3D-LENS: A 3D Lifting-based Elevated Novel-view Synthesis method for Single-View Aerial-Ground Re-Identification,William Grolleau; Astrid Sabourin; Guillaume Lapouge; Catherine Achard,4,William Grolleau,"Aerial-Ground Re-Identification (AG-ReID) is constrained by the viewpoint-domain gap, as drastic viewpoint disparities occlude or distort discriminative features, making cross-viewpoint image retrieval challenging. While existing methods rely on paired cross-view annotations, real-world deployme...",1418,174,cs.CV,cs.CV,1,2026-04-29,2026-04-29,2026,4,0,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.26520v1,https://arxiv.org/pdf/2604.26520v1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7696,2509.23762v3,Accuracy-Robustness Trade Off via Spiking Neural Network Gradient Sparsity Trail,Luu Trong Nhan; Luu Trung Duong; Pham Ngoc Nam; Truong Cong Thang,4,Luu Trong Nhan,"Spiking Neural Networks (SNNs) have attracted growing interest in both computational neuroscience and artificial intelligence, primarily due to their inherent energy efficiency and compact memory footprint. However, achieving adversarial robustness in SNNs, (particularly for vision-related tasks...",1116,142,cs.NE,cs.NE; cs.AI; cs.CV,3,2025-09-28,2025-12-03,2025,9,0,Not Available,Work under peer-review,0,Not Available,https://arxiv.org/abs/2509.23762v3,https://arxiv.org/pdf/2509.23762v3,0,1,66,214
7697,2509.23791v2,CaRe-BN: Precise Moving Statistics for Stabilizing Spiking Neural Networks in Reinforcement Learning,Zijie Xu; Xinyu Shi; Yiting Dong; Zihan Huang; Zhaofei Yu,5,Zijie Xu,"Spiking Neural Networks (SNNs) offer low-latency and energy-efficient decision-making on neuromorphic hardware by mimicking the event-driven dynamics of biological neurons. However, the discrete and non-differentiable nature of spikes leads to unstable gradient propagation in directly trained SN...",1678,217,cs.NE,cs.NE,1,2025-09-28,2026-03-04,2025,9,0,Not Available,Accepted by ICLR2026,0,Not Available,https://arxiv.org/abs/2509.23791v2,https://arxiv.org/pdf/2509.23791v2,0,1,157,214
7698,2509.23896v2,A Computational Perspective on NeuroAI and Synthetic Biological Intelligence,Dhruvik Patel; Md Sayed Tanveer; Jesus Gonzalez-Ferrer; Alon Loeffler; Brett J. Kagan; Mohammed A. Mostajo-Radji; Ge Wang,7,Dhruvik Patel,"NeuroAI is an emerging field at the intersection of neuroscience and artificial intelligence, where insights from brain function guide the design of intelligent systems. A central area within this field is synthetic biological intelligence (SBI), which combines the adaptive learning properties o...",980,128,q-bio.NC,q-bio.NC; cs.ET; cs.NE,3,2025-09-28,2025-10-09,2025,9,0,Not Available,"Submitted to Nature Communications, under ""NeuroAI and Embodied Intelligence"" collection",0,Not Available,https://arxiv.org/abs/2509.23896v2,https://arxiv.org/pdf/2509.23896v2,0,1,11,214
7699,2509.23796v1,From Frustration to Fun: An Adaptive Problem-Solving Puzzle Game Powered by Genetic Algorithm,Matthew McConnell; Richard Zhao,2,Matthew McConnell,"This paper explores adaptive problem solving with a game designed to support the development of problem-solving skills. Using an adaptive, AI-powered puzzle game, our adaptive problem-solving system dynamically generates pathfinding-based puzzles using a genetic algorithm, tailoring the difficul...",1088,146,cs.AI,cs.AI; cs.MM; cs.NE,3,2025-09-28,2025-09-28,2025,9,1,"Proceedings of the Twenty-First AAAI Conference on Artificial Intelligence and Interactive Digital Entertainment (AIIDE-25), Edmonton, Canada, November, 2025",Accepted at the AAAI Conference on Artificial Intelligence and Interactive Digital Entertainment (AIIDE-25),1,10.1609/aiide.v21i1.36831,https://arxiv.org/abs/2509.23796v1,https://arxiv.org/pdf/2509.23796v1,0,0,0,214
7700,2509.23516v4,Network-Optimised Spiking Neural Network for Event-Driven Networking,Muhammad Bilal,1,Muhammad Bilal,"Delay-coupled systems often require low-latency decisions from sparse telemetry, where dense fixed-step neural inference is wasteful and can degrade near stability margins. We introduce Network-Optimised Spiking (NOS), a trainable two-state event-driven dynamical unit for delayed, graph-coupled ...",1354,169,cs.NE,cs.NE; cs.LG; cs.NI; math.OC,4,2025-09-27,2026-01-24,2025,9,0,Not Available,"56 pages, 16 figures, 9 tables",0,Not Available,https://arxiv.org/abs/2509.23516v4,https://arxiv.org/pdf/2509.23516v4,0,1,119,215

In [22]:
num_categories = df["primary_category"].nunique()

print(f"Number of Categories: {num_categories}")

Number of Categories: 107

In [23]:
print(
    f"Average Authors: {df['num_authors'].mean():.2f}"
)

print(
    f"Median Authors: {df['num_authors'].median():.0f}"
)

Average Authors: 5.12
Median Authors: 4

In [24]:
updated_count = (
    df["is_updated"]
    .sum()
)

print(
    f"Updated Papers: {updated_count:,}"
)

Updated Papers: 839

In [25]:
updated_percentage = (
    df["is_updated"]
    .mean() * 100
)

print(
    f"Updated Paper Rate: {updated_percentage:.2f}%"
)

Updated Paper Rate: 10.89%

## **How concentrated is AI research across categories?**

In [26]:
top_categories = (
    df["primary_category"]
    .value_counts()
    .head(15)
    .index
)

team_df = df[
    df["primary_category"].isin(top_categories)
]

In [27]:
top_categories = (
    df["primary_category"]
    .value_counts()
    .head(15)
    .reset_index()
)

top_categories.columns = [
    "category",
    "paper_count"
]

top_categories

   category  paper_count
0     cs.CV         1418
1     cs.LG         1392
2     cs.CL         1119
3     cs.RO          633
4     cs.AI          555
5     cs.NE          511
6     cs.IR          456
7   stat.ML          398
8     cs.CR          149
9     cs.SE           93
10  stat.ME           78
11    cs.HC           59
12  math.OC           55
13    cs.CY           46
14    cs.SD           46

In [28]:
fig = px.bar(
    top_categories,
    x="paper_count",
    y="category",
    orientation="h",
    title="Top 15 Research Categories"
)

fig.show()

In [29]:
category_counts = (
    df["primary_category"]
    .value_counts()
    .reset_index()
)

category_counts.columns = [
    "category",
    "paper_count"
]

category_counts["percentage"] = (
    category_counts["paper_count"]
    / category_counts["paper_count"].sum()
    * 100
)

category_counts.head()

  category  paper_count  percentage
0    cs.CV         1418   18.413193
1    cs.LG         1392   18.075575
2    cs.CL         1119   14.530580
3    cs.RO          633    8.219712
4    cs.AI          555    7.206856

In [30]:
top3_share = (
    category_counts
    .head(3)["percentage"]
    .sum()
)

print(f"Top 3 Categories Share: {top3_share:.2f}%")

Top 3 Categories Share: 51.02%

In [31]:
top5_share = (
    category_counts
    .head(5)["percentage"]
    .sum()
)

print(f"Top 5 Categories Share: {top5_share:.2f}%")

Top 5 Categories Share: 66.45%

In [32]:
top10_share = (
    category_counts
    .head(10)["percentage"]
    .sum()
)

print(f"Top 10 Categories Share: {top10_share:.2f}%")

Top 10 Categories Share: 87.31%

In [33]:
category_counts = (
    df["primary_category"]
    .value_counts()
    .reset_index()
)

category_counts.columns = [
    "category",
    "paper_count"
]

category_counts

    category  paper_count
0      cs.CV         1418
1      cs.LG         1392
2      cs.CL         1119
3      cs.RO          633
4      cs.AI          555
..       ...          ...
102  math.GT            1
103  nlin.CG            1
104    gr-qc            1
105  nlin.AO            1
106    cs.OS            1

[107 rows x 2 columns]

In [34]:
top15 = category_counts.head(15)


fig = px.bar(
    top15,
    x="paper_count",
    y="category",
    orientation="h",
    title="Top 15 AI Research Categories"
)

fig.show()

# 4. NLP Analysis

In [35]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

## NLP 1 - Text Cleaning

In [36]:
df["abstract"].iloc[0]

"Diffusion large language models (dLLMs) offer parallel decoding and bidirectional context, but state-of-the-art dLLMs require billions of parameters for competitive performance. While existing distillation methods for dLLMs reduce inference steps within a single architecture, none address cross-architecture knowledge transfer, in which the teacher and student differ in architecture, attention mechanism, and tokenizer. We present TIDE, the first framework for cross-architecture dLLM distillation, comprising three modular components: (1) TIDAL, which jointly modulates distillation strength across training progress and diffusion timestep to account for the teacher's noise-dependent reliability; (2) CompDemo, which enriches the teacher's context via complementary mask splitting to improve predictions under heavy masking; and (3) Reverse CALM, a cross-tokenizer objective that inverts chunk-level likelihood matching, yielding bounded gradients and dual-end noise filtering. Distilling 8B dense and 16B MoE teachers into a 0.6B student via two heterogeneous pipelines outperforms the baseline by an average of 1.53 points across eight benchmarks, yielding notable gains in code generation, where HumanEval scores reach 48.78 compared to 32.3 for the AR baseline."

In [37]:
stop_words = set(stopwords.words("english"))

In [38]:
def clean_text(text):

    # lowercase
    text = text.lower()

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove numbers
    text = re.sub(r"\d+", "", text)

    # tokenize
    words = word_tokenize(text)

    # remove stopwords
    words = [
        word
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [39]:
df["clean_abstract"] = (
    df["abstract"]
    .apply(clean_text)
)

In [40]:
print("ORIGINAL:\n")
print(df["abstract"].iloc[0])

print("\n" + "="*80 + "\n")

print("CLEANED:\n")
print(df["clean_abstract"].iloc[0])

ORIGINAL:

Diffusion large language models (dLLMs) offer parallel decoding and bidirectional context, but state-of-the-art dLLMs require billions of parameters for competitive performance. While existing distillation methods for dLLMs reduce inference steps within a single architecture, none address cross-architecture knowledge transfer, in which the teacher and student differ in architecture, attention mechanism, and tokenizer. We present TIDE, the first framework for cross-architecture dLLM distillation, comprising three modular components: (1) TIDAL, which jointly modulates distillation strength across training progress and diffusion timestep to account for the teacher's noise-dependent reliability; (2) CompDemo, which enriches the teacher's context via complementary mask splitting to improve predictions under heavy masking; and (3) Reverse CALM, a cross-tokenizer objective that inverts chunk-level likelihood matching, yielding bounded gradients and dual-end noise filtering. Distilling 8B dense and 16B MoE teachers into a 0.6B student via two heterogeneous pipelines outperforms the baseline by an average of 1.53 points across eight benchmarks, yielding notable gains in code generation, where HumanEval scores reach 48.78 compared to 32.3 for the AR baseline.

================================================================================

CLEANED:

diffusion large language models dllms offer parallel decoding bidirectional context state art dllms require billions parameters competitive performance existing distillation methods dllms reduce inference steps within single architecture none address cross architecture knowledge transfer teacher student differ architecture attention mechanism tokenizer present tide first framework cross architecture dllm distillation comprising three modular components tidal jointly modulates distillation strength across training progress diffusion timestep account teacher noise dependent reliability compdemo enriches teacher context via complementary mask splitting improve predictions heavy masking reverse calm cross tokenizer objective inverts chunk level likelihood matching yielding bounded gradients dual end noise filtering distilling b dense b moe teachers b student via two heterogeneous pipelines outperforms baseline average points across eight benchmarks yielding notable gains code generation humaneval scores reach compared ar baseline

In [41]:


vectorizer = CountVectorizer()

X = vectorizer.fit_transform(
    df["clean_abstract"]
)

word_counts = X.sum(axis=0)

word_freq = pd.DataFrame({
    "word": vectorizer.get_feature_names_out(),
    "count": word_counts.A1
})

word_freq = (
    word_freq
    .sort_values(
        by="count",
        ascending=False
    )
)

word_freq.head(30)

              word  count
18071       models   6952
18062        model   6138
2370         based   5735
6489          data   4887
11013    framework   4570
301         across   4499
15726     learning   4188
21176  performance   3803
29778     training   3415
15525     language   3337
22673      propose   3115
17479      methods   3089
15545        large   2885
23673    reasoning   2876
18513        multi   2854
24669      results   2824
31079        using   2680
29419         time   2672
12685         high   2659
26425         show   2638
9810      existing   2634
15852        level   2448
7009   demonstrate   2383
23611         real   2356
14503    introduce   2337
9871   experiments   2320
30251          two   2320
239       accuracy   2186
28922        tasks   2179
28758      systems   2164

In [42]:
research_stopwords = {
    "paper",
    "papers",
    "method",
    "methods",
    "approach",
    "approaches",
    "work",
    "study",
    "propose",
    "proposed",
    "show",
    "results",
    "result",
    "demonstrate",
    "first",
    "however",
    "existing",
    "introduce",
    "introduced",
    "using",
    "based",
    "github",
    "https",
    "com",
    "available",
    "framework",
    "performance",
    "experiments",
    "experiment",
    "state",
    "art",
    "task",
    "tasks",
    "system",
    "systems"
}

all_stopwords = stop_words.union(
    research_stopwords
)

Clean text V2

In [43]:
def clean_text_v2(text):

    text = text.lower()

    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\d+", "", text)

    words = word_tokenize(text)

    words = [
        word
        for word in words
        if word not in all_stopwords
    ]

    return " ".join(words)

In [44]:
df["clean_abstract_v2"] = (
    df["abstract"]
    .apply(clean_text_v2)
)

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(
    df["clean_abstract_v2"]
)

word_counts = X.sum(axis=0)

word_freq = pd.DataFrame({
    "word": vectorizer.get_feature_names_out(),
    "count": word_counts.A1
})

word_freq = (
    word_freq
    .sort_values(
        by="count",
        ascending=False
    )
)

word_freq.head(30)

               word  count
18052        models   6952
18043         model   6138
6483           data   4887
301          across   4499
15709      learning   4188
29745      training   3415
15508      language   3337
15528         large   2885
23649     reasoning   2876
18494         multi   2854
29386          time   2672
12672          high   2659
15835         level   2448
23587          real   2356
30218           two   2320
239        accuracy   2186
11467    generation   2109
9572     evaluation   2007
16151           llm   1999
20166  optimization   1972
16165          llms   1951
13967   information   1875
19042        neural   1793
13074         human   1788
19843         often   1785
262        achieves   1776
26012      semantic   1753
32244         world   1678
23141       quality   1676
416         address   1669

In [46]:
print(df["clean_abstract"].iloc[0])

print("\n" + "="*100 + "\n")

print(df["clean_abstract_v2"].iloc[0])

diffusion large language models dllms offer parallel decoding bidirectional context state art dllms require billions parameters competitive performance existing distillation methods dllms reduce inference steps within single architecture none address cross architecture knowledge transfer teacher student differ architecture attention mechanism tokenizer present tide first framework cross architecture dllm distillation comprising three modular components tidal jointly modulates distillation strength across training progress diffusion timestep account teacher noise dependent reliability compdemo enriches teacher context via complementary mask splitting improve predictions heavy masking reverse calm cross tokenizer objective inverts chunk level likelihood matching yielding bounded gradients dual end noise filtering distilling b dense b moe teachers b student via two heterogeneous pipelines outperforms baseline average points across eight benchmarks yielding notable gains code generation humaneval scores reach compared ar baseline

====================================================================================================

diffusion large language models dllms offer parallel decoding bidirectional context dllms require billions parameters competitive distillation dllms reduce inference steps within single architecture none address cross architecture knowledge transfer teacher student differ architecture attention mechanism tokenizer present tide cross architecture dllm distillation comprising three modular components tidal jointly modulates distillation strength across training progress diffusion timestep account teacher noise dependent reliability compdemo enriches teacher context via complementary mask splitting improve predictions heavy masking reverse calm cross tokenizer objective inverts chunk level likelihood matching yielding bounded gradients dual end noise filtering distilling b dense b moe teachers b student via two heterogeneous pipelines outperforms baseline average points across eight benchmarks yielding notable gains code generation humaneval scores reach compared ar baseline

## Bigrams

In [47]:
bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2),
    stop_words="english"
)

X_bigram = bigram_vectorizer.fit_transform(
    df["clean_abstract_v2"]
)

In [48]:
bigram_counts = X_bigram.sum(axis=0)

bigram_freq = pd.DataFrame({
    "bigram": bigram_vectorizer.get_feature_names_out(),
    "count": bigram_counts.A1
})

bigram_freq = (
    bigram_freq
    .sort_values(
        by="count",
        ascending=False
    )
)

bigram_freq.head(30)

                          bigram  count
298827           language models   1721
299562            large language   1438
442602                real world   1308
347246               models llms    797
361124           neural networks    707
299684               large scale    653
215144               fine tuning    645
454528    reinforcement learning    598
322342          machine learning    513
215094              fine grained    488
597937           vision language    479
442574                 real time    469
361123            neural network    423
298824            language model    417
131915             deep learning    390
179076                   end end    385
251574          high dimensional    356
373871               open source    352
353117               multi agent    351
608349                 zero shot    349
356601          natural language    326
251755              high quality    324
129867           decision making    315
567877             training data    270
102768  consistently outperforms    268
603691               widely used    257
470195       retrieval augmented    234
561235               time series    233
222171         foundation models    224
458893       remains challenging    206

Trigrams

In [49]:
trigram_vectorizer = CountVectorizer(
    ngram_range=(3, 3)
)

X_trigram = trigram_vectorizer.fit_transform(
    df["clean_abstract_v2"]
)

trigram_counts = X_trigram.sum(axis=0)

trigram_freq = pd.DataFrame({
    "trigram": trigram_vectorizer.get_feature_names_out(),
    "count": trigram_counts.A1
})

trigram_freq = (
    trigram_freq
    .sort_values(
        by="count",
        ascending=False
    )
)

trigram_freq.head(30)

                               trigram  count
421560           large language models   1216
420229            language models llms    795
856704          vision language models    222
421559            large language model    221
672721  retrieval augmented generation    186
651459       reinforcement learning rl    168
420386            language models vlms    141
747970         spiking neural networks    135
62865         augmented generation rag    132
419868              language model llm    120
775280          supervised fine tuning    113
507959       multimodal large language    112
519321            neural networks snns    103
634696             real world datasets     95
420246           language models mllms     85
657738         remains challenging due     81
634599         real world applications     77
856659          vision language action     73
635000            real world scenarios     67
495584        models llms increasingly     66
856702           vision language model     63
186654            deep learning models     61
457895         machine learning models     61
634710           real world deployment     58
341530           graph neural networks     58
186817            deep neural networks     57
159249   convolutional neural networks     56
54901       artificial neural networks     56
506302    multi objective optimization     55
419258             language action vla     54

## Top Categories Specific NLP

In [50]:
cv_df = df[
    df["primary_category"] == "cs.CV"
].copy()

lg_df = df[
    df["primary_category"] == "cs.LG"
].copy()

cl_df = df[
    df["primary_category"] == "cs.CL"
].copy()

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

def get_top_ngrams(text_series,
                   ngram_range=(3,3),
                   top_n=20):

    vectorizer = CountVectorizer(
        ngram_range=ngram_range
    )

    X = vectorizer.fit_transform(
        text_series
    )

    counts = X.sum(axis=0)

    ngrams = pd.DataFrame({
        "phrase": vectorizer.get_feature_names_out(),
        "count": counts.A1
    })

    ngrams = (
        ngrams
        .sort_values(
            by="count",
            ascending=False
        )
        .head(top_n)
        .reset_index(drop=True)
    )

    return ngrams

In [52]:
cv_trigrams = get_top_ngrams(
    cv_df["clean_abstract_v2"],
    ngram_range=(3,3)
)

cv_trigrams

                           phrase  count
0          vision language models    138
1           large language models    103
2            language models vlms     85
3       multimodal large language     75
4           language models mllms     58
5           vision language model     33
6       visual question answering     32
7         remains challenging due     30
8   convolutional neural networks     29
9           large vision language     29
10         gaussian splatting dgs     25
11           deep learning models     24
12           large language model     24
13           real world scenarios     23
14     medical image segmentation     21
15           novel view synthesis     21
16         image super resolution     21
17           neural networks cnns     21
18          cross modal alignment     20
19           language models llms     20

In [53]:
lg_trigrams = get_top_ngrams(
    lg_df["clean_abstract_v2"],
    ngram_range=(3,3)
)

lg_trigrams

                         phrase  count
0         large language models    163
1          language models llms     95
2     reinforcement learning rl     68
3         graph neural networks     36
4        supervised fine tuning     28
5       machine learning models     28
6           real world datasets     25
7          synthetic real world     24
8          deep learning models     23
9          neural networks gnns     21
10         deep neural networks     21
11         large language model     19
12      time series forecasting     17
13              fine tuning sft     16
14  stochastic gradient descent     16
15         graph neural network     16
16              real world data     15
17      real world applications     15
18        efficient fine tuning     14
19      physics informed neural     14

In [54]:
cl_trigrams = get_top_ngrams(
    cl_df["clean_abstract_v2"],
    ngram_range=(3,3)
)

cl_trigrams

                            phrase  count
0            large language models    498
1             language models llms    356
2   retrieval augmented generation     59
3             large language model     54
4         augmented generation rag     41
5           supervised fine tuning     39
6         models llms increasingly     37
7               language model llm     31
8        reinforcement learning rl     26
9      natural language processing     24
10          vision language models     23
11               chain thought cot     19
12           small language models     19
13          low resource languages     18
14       multimodal large language     16
15            language models slms     16
16             language models lms     16
17    language models increasingly     14
18            language models vlms     14
19     capabilities large language     14

Pecentage of LLM showing up in the top 3 categories

In [55]:
llm_terms = [
    "llm",
    "llms",
    "large language model",
    "large language models"
]

def contains_llm(text):

    text = text.lower()

    return any(
        term in text
        for term in llm_terms
    )

## Calculating Percetages of LLM in each category

In [56]:
cv_df["mentions_llm"] = (
    cv_df["clean_abstract_v2"]
    .apply(contains_llm)
)

In [57]:
cv_percentage = (
    cv_df["mentions_llm"]
    .mean() * 100
)

In [58]:
cl_df["mentions_llm"] = (
    cl_df["clean_abstract_v2"]
    .apply(contains_llm)
)

In [59]:
cl_percentage = (
    cl_df["mentions_llm"]
    .mean() * 100
)

In [60]:
lg_df["mentions_llm"] = (
    lg_df["clean_abstract_v2"]
    .apply(contains_llm)
)

In [61]:
lg_percentage = (
    lg_df["mentions_llm"]
    .mean() * 100
)

In [62]:
llm_presence = pd.DataFrame({
    "Category": ["cs.CL", "cs.LG", "cs.CV"],
    "LLM_Percentage": [
        cl_percentage,
        lg_percentage,
        cv_percentage
    ]
})

llm_presence

  Category  LLM_Percentage
0    cs.CL       65.326184
1    cs.LG       18.893678
2    cs.CV       12.341326

In [63]:
fig = px.bar(
    llm_presence,
    x="LLM_Percentage",
    y="Category",
    orientation="h",
    title="LLM Presence Across Major AI Research Categories",
    text="LLM_Percentage"
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_xaxes(
    range=[0, 100]
)

fig.show()

## Percentage of Top trigrams

In [64]:
trigram_freq.head(20)

                               trigram  count
421560           large language models   1216
420229            language models llms    795
856704          vision language models    222
421559            large language model    221
672721  retrieval augmented generation    186
651459       reinforcement learning rl    168
420386            language models vlms    141
747970         spiking neural networks    135
62865         augmented generation rag    132
419868              language model llm    120
775280          supervised fine tuning    113
507959       multimodal large language    112
519321            neural networks snns    103
634696             real world datasets     95
420246           language models mllms     85
657738         remains challenging due     81
634599         real world applications     77
856659          vision language action     73
635000            real world scenarios     67
495584        models llms increasingly     66

In [65]:
def contains_llm(text):

    text = str(text).lower()

    return any(
        term in text
        for term in llm_terms
    )

df["mentions_llm"] = (
    df["clean_abstract_v2"]
    .apply(contains_llm)
)

llm_percentage = (
    df["mentions_llm"]
    .mean() * 100
)

print(
    f"LLM-related papers: {llm_percentage:.2f}%"
)

LLM-related papers: 26.81%

In [66]:
vlm_terms = [
    "vision language model",
    "vision language models",
    "vlm",
    "vlms",
    "multimodal large language"
]

def contains_vlm(text):

    text = str(text).lower()

    return any(
        term in text
        for term in vlm_terms
    )

df["mentions_vlm"] = (
    df["clean_abstract_v2"]
    .apply(contains_vlm)
)

vlm_percentage = (
    df["mentions_vlm"]
    .mean() * 100
)

print(f"VLM-related papers: {vlm_percentage:.2f}%")

VLM-related papers: 5.51%

In [67]:
rag_terms = [
    "retrieval augmented generation",
    "augmented generation rag"
]

def contains_rag(text):

    text = str(text).lower()

    return any(
        term in text
        for term in rag_terms
    )

df["mentions_rag"] = (
    df["clean_abstract_v2"]
    .apply(contains_rag)
)

rag_percentage = (
    df["mentions_rag"]
    .mean() * 100
)

print(f"RAG-related papers: {rag_percentage:.2f}%")

RAG-related papers: 2.22%

In [68]:
rl_terms = [
    "reinforcement learning",
    "reinforcement learning rl"
]

def contains_rl(text):

    text = str(text).lower()

    return any(
        term in text
        for term in rl_terms
    )

df["mentions_rl"] = (
    df["clean_abstract_v2"]
    .apply(contains_rl)
)

rl_percentage = (
    df["mentions_rl"]
    .mean() * 100
)

print(f"RL-related papers: {rl_percentage:.2f}%")

RL-related papers: 6.73%

In [69]:
gnn_terms = [
    "graph neural network",
    "graph neural networks",
    "gnn",
    "gnns"
]

def contains_gnn(text):

    text = str(text).lower()

    return any(
        term in text
        for term in gnn_terms
    )

df["mentions_gnn"] = (
    df["clean_abstract_v2"]
    .apply(contains_gnn)
)

gnn_percentage = (
    df["mentions_gnn"]
    .mean() * 100
)

print(f"GNN-related papers: {gnn_percentage:.2f}%")

GNN-related papers: 1.45%

In [70]:
finetune_terms = [
    "fine tuning",
    "supervised fine tuning",
    "efficient fine tuning",
    "sft"
]

def contains_finetune(text):

    text = str(text).lower()

    return any(
        term in text
        for term in finetune_terms
    )

df["mentions_finetune"] = (
    df["clean_abstract_v2"]
    .apply(contains_finetune)
)

finetune_percentage = (
    df["mentions_finetune"]
    .mean() * 100
)

print(f"Fine-tuning-related papers: {finetune_percentage:.2f}%")

Fine-tuning-related papers: 6.64%

In [71]:
theme_summary = pd.DataFrame({
    "Theme": [
        "LLM",
        "VLM",
        "RAG",
        "Reinforcement Learning",
        "Graph Neural Networks",
        "Fine-Tuning"
    ],
    "Percentage_of_Papers": [
        df["mentions_llm"].mean() * 100,
        df["mentions_vlm"].mean() * 100,
        df["mentions_rag"].mean() * 100,
        df["mentions_rl"].mean() * 100,
        df["mentions_gnn"].mean() * 100,
        df["mentions_finetune"].mean() * 100
    ],
    "Paper_Count": [
        df["mentions_llm"].sum(),
        df["mentions_vlm"].sum(),
        df["mentions_rag"].sum(),
        df["mentions_rl"].sum(),
        df["mentions_gnn"].sum(),
        df["mentions_finetune"].sum()
    ]
})

theme_summary = (
    theme_summary
    .sort_values(
        by="Percentage_of_Papers",
        ascending=False
    )
    .reset_index(drop=True)
)

theme_summary

                    Theme  Percentage_of_Papers  Paper_Count
0                     LLM             26.814699         2065
1  Reinforcement Learning              6.726399          518
2             Fine-Tuning              6.635502          511
3                     VLM              5.505778          424
4                     RAG              2.220491          171
5   Graph Neural Networks              1.454357          112

In [72]:
fig = px.bar(
    theme_summary,
    x="Percentage_of_Papers",
    y="Theme",
    orientation="h",
    text="Percentage_of_Papers",
    title="Research Theme Presence Across AI Papers"
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_xaxes(
    range=[0, 100],
    ticksuffix="%"
)

fig.show()

## Export Tables

In [73]:
# ==========================================
# EXPORT ALL DASHBOARD TABLES
# ==========================================

tables = {
    "top_categories": top_categories,
    "category_counts": category_counts,
    "word_freq": word_freq,
    "bigram_freq": bigram_freq,
    "trigram_freq": trigram_freq,
    "cv_trigrams": cv_trigrams,
    "lg_trigrams": lg_trigrams,
    "cl_trigrams": cl_trigrams,
    "theme_summary": theme_summary,
    "llm_presence": llm_presence
}

for name, table in tables.items():

    table.to_csv(
        f"{name}.csv",
        index=False
    )

    print(
        f"✅ Saved: {name}.csv"
    )

print("\n====================================")
print("All tables exported successfully!")
print("====================================")

✅ Saved: top_categories.csv
✅ Saved: category_counts.csv
✅ Saved: word_freq.csv
✅ Saved: bigram_freq.csv
✅ Saved: trigram_freq.csv
✅ Saved: cv_trigrams.csv
✅ Saved: lg_trigrams.csv
✅ Saved: cl_trigrams.csv
✅ Saved: theme_summary.csv
✅ Saved: llm_presence.csv

====================================
All tables exported successfully!
====================================

In [74]:
from google.colab import files

csv_files = [
    "top_categories.csv",
    "category_counts.csv",
    "word_freq.csv",
    "bigram_freq.csv",
    "trigram_freq.csv",
    "cv_trigrams.csv",
    "lg_trigrams.csv",
    "cl_trigrams.csv",
    "theme_summary.csv",
    "llm_presence.csv"
]

for file in csv_files:
files.download(file)

In [75]:
df.to_csv(
    "clean_ai_research.csv",
    index=False
)

In [76]:
from google.colab import files

csv_files = [
    "clean_ai_research.csv"
]

for file in csv_files:
    files.download(file)